name: "Shakepay"
date_column: "Date"
date_format: "%Y-%m-%dT%H:%M:%S%z"
columns:
  transaction_type: "Transaction Type"
  amount_debited: "Amount Debited"
  debit_currency: "Debit Currency"
  amount_credited: "Amount Credited"
  credit_currency: "Credit Currency"
  rate: "Buy / Sell Rate"
  spot_rate: "Spot Rate"
  direction: "Direction"
  source_destination: "Source / Destination"
  txid: "Blockchain Transaction ID"
transaction_type_map:
  "purchase/sale": "trade"
  "crypto cashout": "withdrawal"
  "crypto funding": "deposit"
  "fiat funding": "fiat_deposit"
  "fiat cashout": "fiat_withdrawal"
  "other": "other"
fee_model: "spread"
